/**
 * GLSL Shader source code for sakura particle effect
 * Extracted to external file for caching & deduplication across pages
 */
window.__shaders = window.__shaders || {};

// --- Sakura particle vertex shader ---
window.__shaders.sakura_point_vsh = [
"uniform mat4 uProjection;",
"uniform mat4 uModelview;",
"uniform vec3 uResolution;",
"uniform vec3 uOffset;",
"uniform vec3 uDOF;",
"uniform vec3 uFade;",
"",
"attribute vec3 aPosition;",
"attribute vec3 aEuler;",
"attribute vec2 aMisc;",
"",
"varying vec3 pposition;",
"varying float psize;",
"varying float palpha;",
"varying float pdist;",
"",
"varying vec3 normX;",
"varying vec3 normY;",
"varying vec3 normZ;",
"varying vec3 normal;",
"",
"varying float diffuse;",
"varying float specular;",
"varying float rstop;",
"varying float distancefade;",
"",
"void main(void) {",
"    vec4 pos = uModelview * vec4(aPosition + uOffset, 1.0);",
"    gl_Position = uProjection * pos;",
"    gl_PointSize = aMisc.x * uProjection[1][1] / -pos.z * uResolution.y * 0.5;",
"",
"    pposition = pos.xyz;",
"    psize = aMisc.x;",
"    pdist = length(pos.xyz);",
"    palpha = smoothstep(0.0, 1.0, (pdist - 0.1) / uFade.z);",
"",
"    vec3 elrsn = sin(aEuler);",
"    vec3 elrcs = cos(aEuler);",
"    mat3 rotx = mat3(",
"        1.0, 0.0, 0.0,",
"        0.0, elrcs.x, elrsn.x,",
"        0.0, -elrsn.x, elrcs.x",
"    );",
"    mat3 roty = mat3(",
"        elrcs.y, 0.0, -elrsn.y,",
"        0.0, 1.0, 0.0,",
"        elrsn.y, 0.0, elrcs.y",
"    );",
"    mat3 rotz = mat3(",
"        elrcs.z, elrsn.z, 0.0,",
"        -elrsn.z, elrcs.z, 0.0,",
"        0.0, 0.0, 1.0",
"    );",
"    mat3 rotmat = rotx * roty * rotz;",
"    normal = rotmat[2];",
"",
"    mat3 trrotm = mat3(",
"        rotmat[0][0], rotmat[1][0], rotmat[2][0],",
"        rotmat[0][1], rotmat[1][1], rotmat[2][1],",
"        rotmat[0][2], rotmat[1][2], rotmat[2][2]",
"    );",
"    normX = trrotm[0];",
"    normY = trrotm[1];",
"    normZ = trrotm[2];",
"",
"    const vec3 lit = vec3(0.6917144638660746, 0.6917144638660746, -0.20751433915982237);",
"",
"    float tmpdfs = dot(lit, normal);",
"    if(tmpdfs < 0.0) {",
"        normal = -normal;",
"        tmpdfs = dot(lit, normal);",
"    }",
"    diffuse = 0.4 + tmpdfs;",
"",
"    vec3 eyev = normalize(-pos.xyz);",
"    if(dot(eyev, normal) > 0.0) {",
"        vec3 hv = normalize(eyev + lit);",
"        specular = pow(max(dot(hv, normal), 0.0), 20.0);",
"    }",
"    else {",
"        specular = 0.0;",
"    }",
"",
"    rstop = clamp((abs(pdist - uDOF.x) - uDOF.y) / uDOF.z, 0.0, 1.0);",
"    rstop = pow(rstop, 0.5);",
"    distancefade = min(1.0, exp((uFade.x - pdist) * 0.69315 / uFade.y));",
"}"
].join("\n");

// --- Sakura particle fragment shader ---
window.__shaders.sakura_point_fsh = [
"#ifdef GL_ES",
"precision highp float;",
"#endif",
"",
"uniform vec3 uDOF;",
"uniform vec3 uFade;",
"",
"const vec3 fadeCol = vec3(0.15, 0.08, 0.12);",
"",
"varying vec3 pposition;",
"varying float psize;",
"varying float palpha;",
"varying float pdist;",
"",
"varying vec3 normX;",
"varying vec3 normY;",
"varying vec3 normZ;",
"varying vec3 normal;",
"",
"varying float diffuse;",
"varying float specular;",
"varying float rstop;",
"varying float distancefade;",
"",
"void main(void) {",
"    vec3 p = vec3(gl_PointCoord - vec2(0.5, 0.5), 0.0) * 2.0;",
"    vec3 d = vec3(0.0, 0.0, -1.0);",
"    float nd = normZ.z;",
"    if(abs(nd) < 0.0001) discard;",
"",
"    float np = dot(normZ, p);",
"    vec3 tp = p + d * np / nd;",
"    vec2 coord = vec2(dot(normX, tp), dot(normY, tp));",
"",
"    float r = 1.0;",
"    for (int i = 0; i < 5; i++) {",
"        float a = float(i) * 1.256637;",
"        vec2 dir = vec2(cos(a), sin(a));",
"        float y = dot(coord, dir);",
"        float x = dot(coord, vec2(-dir.y, dir.x));",
"        float lobe1 = length(vec2(x - 0.08, y - 0.1)) - 0.15;",
"        float lobe2 = length(vec2(x + 0.08, y - 0.1)) - 0.15;",
"        float tip = length(vec2(x, y + 0.08)) - 0.16;",
"        float pd = min(min(lobe1, lobe2), tip);",
"        float cleft = y - abs(x) * 0.8;",
"        pd = max(pd, cleft + 0.04);",
"        r = min(r, pd);",
"    }",
"",
"    if(r > rstop) discard;",
"",
"    vec3 col = vec3(0.95, 0.72, 0.68);",
"    col = col * diffuse + specular * 0.15;",
"    col = min(col, vec3(1.0));",
"",
"    col = mix(fadeCol, col, distancefade);",
"",
"    float alpha = (rstop > 0.001) ? (0.5 - r / (rstop * 2.0)) : 1.0;",
"    alpha = smoothstep(0.0, 1.0, alpha) * palpha;",
"",
"    gl_FragColor = vec4(col * 0.85, alpha);",
"}"
].join("\n");

// --- FX common vertex shader ---
window.__shaders.fx_common_vsh = [
"uniform vec3 uResolution;",
"attribute vec2 aPosition;",
"",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"",
"void main(void) {",
"    gl_Position = vec4(aPosition, 0.0, 1.0);",
"    texCoord = aPosition.xy * 0.5 + vec2(0.5, 0.5);",
"    texCoord.y = 1.0 - texCoord.y;",
"    screenCoord = aPosition.xy * vec2(uResolution.z, 1.0);",
"}"
].join("\n");

// --- Background fragment shader ---
window.__shaders.bg_fsh = [
"#ifdef GL_ES",
"precision highp float;",
"#endif",
"",
"uniform vec2 uTimes;",
"",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"",
"void main(void) {",
"    vec3 col;",
"    float c;",
"    vec2 tmpv = texCoord * vec2(0.8, 1.0) - vec2(0.95, 1.0);",
"    c = exp(-pow(length(tmpv) * 1.8, 2.0));",
"    col = mix(vec3(0.02, 0.0, 0.03), vec3(0.96, 0.98, 1.0) * 1.5, c);",
"    gl_FragColor = vec4(col * 0.5, 1.0);",
"}"
].join("\n");

// --- Brightness extraction fragment shader ---
window.__shaders.fx_brightbuf_fsh = [
"#ifdef GL_ES",
"precision highp float;",
"#endif",
"uniform sampler2D uSrc;",
"uniform vec2 uDelta;",
"",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"",
"void main(void) {",
"    vec4 col = texture2D(uSrc, texCoord);",
"    gl_FragColor = vec4(col.rgb * 2.0 - vec3(0.5), 1.0);",
"}"
].join("\n");

// --- Directional blur fragment shader ---
window.__shaders.fx_dirblur_r4_fsh = [
"#ifdef GL_ES",
"precision highp float;",
"#endif",
"uniform sampler2D uSrc;",
"uniform vec2 uDelta;",
"uniform vec4 uBlurDir;",
"",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"",
"void main(void) {",
"    vec4 col = texture2D(uSrc, texCoord);",
"    col = col + texture2D(uSrc, texCoord + uBlurDir.xy * uDelta);",
"    col = col + texture2D(uSrc, texCoord - uBlurDir.xy * uDelta);",
"    col = col + texture2D(uSrc, texCoord + (uBlurDir.xy + uBlurDir.zw) * uDelta);",
"    col = col + texture2D(uSrc, texCoord - (uBlurDir.xy + uBlurDir.zw) * uDelta);",
"    gl_FragColor = col / 5.0;",
"}"
].join("\n");

// --- FX common fragment shader ---
window.__shaders.fx_common_fsh = [
"#ifdef GL_ES",
"precision highp float;",
"#endif",
"uniform sampler2D uSrc;",
"uniform vec2 uDelta;",
"",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"",
"void main(void) {",
"    gl_FragColor = texture2D(uSrc, texCoord);",
"}"
].join("\n");

// --- PP final vertex shader ---
window.__shaders.pp_final_vsh = [
"uniform vec3 uResolution;",
"attribute vec2 aPosition;",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"void main(void) {",
"    gl_Position = vec4(aPosition, 0.0, 1.0);",
"    texCoord = aPosition.xy * 0.5 + vec2(0.5, 0.5);",
"    screenCoord = aPosition.xy * vec2(uResolution.z, 1.0);",
"}"
].join("\n");

// --- PP final fragment shader ---
window.__shaders.pp_final_fsh = [
"#ifdef GL_ES",
"precision highp float;",
"#endif",
"uniform sampler2D uSrc;",
"uniform sampler2D uBloom;",
"uniform vec2 uDelta;",
"varying vec2 texCoord;",
"varying vec2 screenCoord;",
"void main(void) {",
"    vec4 srccol = texture2D(uSrc, texCoord) * 2.0;",
"    vec4 bloomcol = texture2D(uBloom, texCoord);",
"    vec4 col;",
"    col = srccol + bloomcol * (vec4(1.0) + srccol);",
"    col *= smoothstep(1.0, 0.0, pow(length((texCoord - vec2(0.5)) * 2.0), 1.2) * 0.5);",
"    col = pow(col, vec4(0.45454545454545));",
"    gl_FragColor = vec4(col.rgb, 1.0);",
"    gl_FragColor.a = 1.0;",
"}"
].join("\n");
